#! /usr/bin/env bash

ver=$(ag -o '\d+\.\d+\.\d+' <(docker run --rm klakegg/hugo version))
sed -i '' "s/HUGO_VERSION = \".*\"$/HUGO_VERSION = \"$ver\"/" netlify.toml

git add --all
git commit -m "bump hugo to $ver"
git diff-tree --no-commit-id --name-only -r HEAD
